from __future__ import annotations

"""event

Revision ID: a09769e5e09c
Revises:
Create Date: 2026-05-07 19:43:03.486038
"""

revision: str = "a09769e5e09c"
down_revision: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
